apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oauth2-proxy
  template:
    metadata:
      labels:
        run: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=google
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --client-id=<CLIENT-ID>
        - --client-secret=<CLIENT-SECRET>
        - --cookie-domain=.measurementlab.net
        - --cookie-refresh=1h
        - --cookie-secret=<COOKIE-SECRET>
        - --email-domain=measurementlab.net
        - --email-domain=mlab-sandbox.iam.gserviceaccount.com
        - --set-xauthrequest=true
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.0.0
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
